name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v6
      - run: npm i -fg corepack && corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "pnpm"
      # https://serverfault.com/questions/856194/securely-add-a-host-e-g-github-to-the-ssh-known-hosts-file
      - name: Add github.com in known_hosts
        run: curl --silent https://api.github.com/meta | jq --raw-output '"github.com "+.ssh_keys[]' >> ~/.ssh/known_hosts
      - run: pnpm install
      - run: pnpm lint
        if: runner.os != 'Windows'
      - run: pnpm build
      - run: pnpm vitest --coverage
      - uses: codecov/codecov-action@v5
